# Generated by Django 4.2.1 on 2023-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
